service: dream-job

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-south-1
  stage: prod
  environment:
    MONGODB_URL: ${file(./config.js):getEnvVars.${self:provider.stage}.MONGODB_URL}

functions:
  graphql:
    handler: handler.graphqlHandler
    role: ServiceRole
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get

custom:
  serverless-offline:
    port: 5000

plugins:
  - serverless-offline
